### ISSUE TITLE
Hanging on Connecting

### ISSUE THREAD

**Issue by zackotronic** [yakyak/yakyak#1177]
Tried on multiple computers, it is hanging on connecting.

**Comment by MisterShifty** [comment]
I'm running into the same issue. When I launch it from a terminal (I'm running Linux Mint 18.1) I get this:

![image](https://user-images.githubusercontent.com/66980521/84720487-c6ba7700-af43-11ea-9b49-af015b4a2e31.png)

**Comment by JimRichards22** [comment]
I see this happening as well, getting the HTTP 403 errors. I'm surprised it's using `plus.google.com` domain name. Google Plus is relaunching as Currents soon

> We’re writing to let you know that Currents will become generally available (GA) on July 6, 2020. 

I can see right at the start for a new session (deleting my old credentials)
```
$ yakyak 
hangupsjs:: connecting
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
```

**Comment by Matthew92007** [comment]
Same issue on macOS 10.14.6, 10.15.5, and Windows 10.

**Comment by vasudev-gm** [comment]
Observing it on Ubuntu 18.04.4. Haven't tested it on Windows 10. I use Linux primarily.
I thank zackotronic for creating a PR. I was nearly pulling my hairs out since I thought it was internet connectivity issue at my end!

**Comment by bdaboah** [comment]
Someone know how put Yakyak in debug/verbose mode ? 

the data are truncated : 
`{
 "error": {
  "errors": [
   {
    "domain": "us`

**Comment by kornfleks** [comment]
Same issue on MacOS beta 10.15.5 (19F94a)

**Comment by baspetersnl** [comment]
Same on MacOS 10.15.4. Tried version 1.5.7-beta and 1.5.4.

**Comment by Jollibeee** [comment]
Same issue on Ubuntu 18.04  yakyak 1.5.6

**Comment by bdaboah** [comment]
> Same issue on Ubuntu 18.04 yakyak 1.5.6

it isn't the same error ;)

**Comment by patefoniq** [comment]
Same issue on Windows and deleting the profile doesn't help for that.

**Comment by AAlchemy** [comment]
I'll add my "me too" on MacOS

**Comment by dguttierrez** [comment]
Same problem on Win10, MacOS 10.15.5 and Ubutnu Linux.

**Comment by teicher** [comment]
can we please assume its broken for everybody, and stop adding "me toos" now?

**Comment by HomerSp** [comment]
Looks like a server-side change broke it. I've created a pull request here: https://github.com/yakyak/hangupsjs/pull/117 Hopefully that can be pulled in soon so we can get a new release with it fixed.
If you want to test the fix, download this file and put it in app/node_modules/hangupsjs/lib/init.js : https://gist.github.com/dcd568967c68c9c203efd99545403b35

**Comment by AtmaDarkwolf** [comment]
@HomerSp - Do not evne have that file(given you didn't give full path, assume u mean resources/app/etc) - can't find lib folder.

**Comment by jellisii** [comment]
Be sure that when this fix gets into place that it's reflected in https://github.com/snapcrafters/yakyak too.

**Comment by bdaboah** [comment]
> Looks like a server-side change broke it. I've created a pull request here: [yakyak/hangupsjs#117](https://github.com/yakyak/hangupsjs/pull/117) Hopefully that can be pulled in soon so we can get a new release with it fixed.
> If you want to test the fix, download this file and put it in app/node_modules/hangupsjs/lib/init.js : https://gist.github.com/dcd568967c68c9c203efd99545403b35

It's works ;)

**Comment by musasabi** [comment]
Much obliged, @HomerSp 

That did the trick for me on Arch

**Comment by averissimo** [comment]
Should be fixed in v1.5.7 thanks to @HomerSp

**Comment by patefoniq** [comment]
With version 1.5.8 problem was fixed. I cannot confirm if the same is with fixed 1.5.7 but the newest version works like a charm. Thank you, good job team.

**Comment by patefoniq** [comment]
1.5.10 on Windows 7 - Problem is back

![image](https://user-images.githubusercontent.com/11136688/101452559-23fd1700-392e-11eb-8aa7-e09dde55496c.png)

**Comment by teicher** [comment]
no such problems here with 1.5.10 on MacOS Catalina.

**Comment by vasudev-gm** [comment]
> 1.5.10 on Windows 7 - Problem is back
> 
> ![image](https://user-images.githubusercontent.com/11136688/101452559-23fd1700-392e-11eb-8aa7-e09dde55496c.png)
> 
> When I clear the profile the login window shows up but after providing the credentials it's getting stuck.

Try killing the task yakyak using task manager. Have observed the issue on Linux as well. Few days ago, there was 2 instances of yakyak running but it was still showing Connecting..... Killing the process and starting yakyak opened up instantly.
