### ISSUE TITLE
Emoticons are broken in 1.1.3

### ISSUE THREAD

**Issue by vandasian** [yakyak/yakyak#132]
The new emoticon menu is lacking an icon, and when clicked only a few emoticons appear (in B&W), most are still empty squares. Searching through the original pull request, I see that the functionality makes use of the Noto font -- is this required to be installed separately? I tried downloading and installing the font from Google but it did not appear to be a valid font.
Windows 10 Build 10586.104

**Comment by davibe** [comment]
@mhogerheijde can you help me check what happens ? @vandasian which us do you use ?

**Comment by vandasian** [comment]
@davibe I assume you mean OS? In my post I included: Windows 10 Build 10586.104. I'm running YakYak 1.1.3 x64

**Comment by mhogerheijde** [comment]
I did put the font within the source-tree, so it should not be needed to install it yourself. It is a ttf (TrueTypeFont), which should "just work" under Windows I think? IE does not fully support it, but YakYak uses a build in browser (Chromium) to render the app, so that should not be the issue.

I think the first things to check are:
- Is Noto packaged in the release zip?
- Is Noto ttf a valid font at-all on Windows (since @vandasian states it to be an invalid font)
- Is there a better fallback-font for Windows? If I'm not mistaken, Windows 10 aims to be cross-device, and I would thus expect there to be a built-in Emoticon font? (Like iOs and MacOS X have)

The fact that there are black-and-white emoticons and empty-box characters is because those are the glyphs contained within the fallback-font.

I'll try to spin up a VM with Windows and have a look at what and why this happens.

**Comment by mhogerheijde** [comment]
First check: The Noto font is included in the zipfile. So it is either not located correctly, or it - as stated - is not a valid font under Windows.

**Comment by davibe** [comment]
maintaining windows is becoming increasingly difficult

**Comment by mhogerheijde** [comment]
Seems this is related to:

https://code.google.com/p/chromium/issues/detail?id=586291

The message in the console is "Failed to decode downloaded font". YakYak does indeed have the correct path to the .ttf file that contains Noto, but is unable to decode it as a font. I'm not a real css-wizard, so I don't know the appropriate hacks to get the @font-face declaration to work... Maybe we should search for a Windows enabled emoticon-font?

**Comment by mhogerheijde** [comment]
It seems that Windows 10 gets "Segoe UI Emoji" font shipped with it. But when I enable that one; it's ugly and b/w. It should contain color emoji, but my little hack-work didn't get that to work.

It's probably easier to convert the noto ttf to a font that windows does support?

**Comment by mhogerheijde** [comment]
(Well,.. it's easier to _not_ support Windows ;) </rant> )

**Comment by vandasian** [comment]
I've created an issue under Google's Noto github here: [https://github.com/googlei18n/noto-emoji/issues/43](https://github.com/googlei18n/noto-emoji/issues/43)

I wonder if this is the problem with the Noto font installing under Windows: [https://github.com/Ranks/emojione/issues/167#issuecomment-165960089](https://github.com/Ranks/emojione/issues/167#issuecomment-165960089)
If it is, then I wouldn't think Chromium is the problem, and another font like [EmojiOne](https://github.com/Ranks/emojione) wouldn't work either. Please correct me if I'm wrong.

Segoe UI Emoji is ugly if that's the fallback. I edited app.css to use [OpenSansEmoji.ttf](https://github.com/MorbZ/OpenSansEmoji), which I dropped in the same folder as Noto for testing. It worked and contained more glyphs than the fallback, but still is missing some glyphs specified in your menu code (not to mention it's B&W and still ugly.)

**Comment by mhogerheijde** [comment]
The fact that the native Windows emoji (Segoe) doesn't work (at least, in colour), seems to be an issue with Chrom(e|ium) that bypasses the Native font-rendering of the OS. 

https://code.google.com/p/chromium/issues/detail?id=333011

But I don't get why, when it does font-rendering itself, the Noto-font also doesn't work. Anyway, this seems to be something that needs either: a colour emoticon-font that is supported by both Windows _and_ Chromium or a fix in Chromium (or rendering inserting png's for emoticons; or using a different browser on Windows :wink:)

**Comment by algesten** [comment]
where is this?

**Comment by davibe** [comment]
As far as i understand this the noto font only works on linux. On mac things stil llook almost fine because osx uses its own font. On windows the emoticons are shown empty. Is this right @mhogerheijde ?

**Comment by bryanzw15** [comment]
On Windows we get ugly black and white emoticons/emoji or blank boxes which is weird because the built in Windows touch keyboard has proper color emoji. The picture shows the YakYak emoji page as well as the touch keyboard that Windows 10 (and 8 I think) ship with.

![image](https://cloud.githubusercontent.com/assets/14352938/16499907/4d70ca6c-3ed0-11e6-8d80-4f17493bdf40.png)

**Comment by mhogerheijde** [comment]
It has to do with priority I think. It takes the first font that supplies
the emoticon glyphs, so on both Mac and Windows a font is provided that
already has emoticons in it. On Linux there isn't (depending on distro
probably), so it takes the Noto font.

Maybe we can force the css to take the Noto font? But I don't know if that
would allow the Mac font to be first? I assume the font for Mac should not
be overridden by the Noto font, right? So then we should figure out what
font it is that supplies the unwanted glyphs in windows and make its
priority less than the Noto font.

**Comment by mhogerheijde** [comment]
Sorry, I read too quickly and skipped over the part where there seems to be
a Nice font for emoticons on Windows: then it probably is not added to the
CSS correctly?

**Comment by bryanzw15** [comment]
As far as I know, and with the little experimentation I did, it has to do with the Chromium rendering engine that Electron uses. On Windows, if you go to getemoji.com, it renders the black and white emoji on Chromium/Chrome but if you go there on Edge or Firefox it uses the built in Windows emoji that are shown in my picture. So I have a feeling you're right with the priority thing, it's just a matter of getting Electron to prioritize the Windows built in ones over the Chromium ones. I don't know how hard that would be or how to do that though.

**Comment by arnriu** [comment]
This is a chromium issue on windows. Css can't help it.
Hopefully they will add colored emoji support... someday...

BUT, because i like you windows guys :smiling_imp: , I looked into it.
Those are not windows noative emojis but twitter emojis. This is temporary (waiting for chromium team to add native color emoji support), it can be heavy and laggy if you (or a friend) spam emojis since it parses the dom to replace unicode with img tags.

Hope you'll enjoy it !

![emoji](https://cloud.githubusercontent.com/assets/9418756/16507224/7da348b0-3f28-11e6-9b4c-9f97041845bd.png)

**Comment by bryanzw15** [comment]
Those look great! Though it may be all for nothing. Looking through the Chromium bugs it seems like they have it fixed already...
[https://bugs.chromium.org/p/chromium/issues/detail?id=333011](https://bugs.chromium.org/p/chromium/issues/detail?id=333011)
I just downloaded Chrome Canary and the color emoji are present so it seems a fix from Chromium is incoming sometime relatively soon. Though I don't know how long that will take to get to Electron, so these are great until then.

**Comment by averissimo** [comment]
Should colored emojis be working in linux out of the box?

Because it is not working with master branch on my build.

![selection_044](https://cloud.githubusercontent.com/assets/211358/17966697/bdc33bf4-6aba-11e6-8503-e7fc3a0fde9d.png)

**Comment by averissimo** [comment]
had to create file ~/.fonts.conf and add this to it :)

now it works!! -- not sure if this is a general problem, or just with my crazy machine.

found the solution in googlei18n/noto-emoji/issues/36

```
<?xml version='1.0'?> 
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'> 
<fontconfig> 
  <match target="pattern"> 
    <edit name="family" mode="prepend"> 
      <string>Noto Color Emoji</string> 
    </edit> 
  </match> 
</fontconfig> 
```

**Comment by arnriu** [comment]
@averissimo Color emojis are system based. On linux, i think it depends on distros, desktop environments, or manual font installation.

**Comment by averissimo** [comment]
Thanks for the reply!

It might not be obvious for the user that this is system-dependant and less obvious that this is a chromium related issue _(if you see color emoji in chrome, than yakyak should also work fine)_

**Maybe a wiki/documentation page can be created** on system by system tips to use color emojis as installing a font was not enough _(at least for me in Linux/Ubuntu 16.10 yakkety)_

Something like:

- if works out of the box
- _(otherwise)_ font required to install 
  - special configuration needed

**Comment by ctcpip** [comment]
Is it possible that the above commit (or another) caused a regression on Linux?  I previously had color emoji which matched what I see on google.  Now it's the black/white versions as in the screenshots above.

(Lubuntu 16.04)

**Comment by arnriu** [comment]
Yes it could.
The fix above is for windows only: `if process.platform == 'win32'`

But, in the same time, I removed noto font since it is not necessary for Windows and Mac, and I was thinking that it was the same on linux if you have color emoji support on your distro, but maybe I was wrong, we could try to add onto again, at least for linux, and see if it fixes.

**Comment by averissimo** [comment]
I just confirmed that this commit (6245097febf847cd9d027c04df5000de3ae3736b) disabled "out of the box" colored emoji support **in Linux**, defaulting to a system based font (black and white). Tested both this and the parent commit to confirm it.

Which for me required an install and manual fix (that I shared above).

**Comment by Arithmomaniac** [comment]
The Twimoji support seems incomplete. (Win10 / 1.3.3). "😘" is falling back to black-and-white for me.

**Comment by Nefari0uss** [comment]
Here's an imgur link of the result for me: ![Imgur](http://imgur.com/f8TQvju)

**Comment by averissimo** [comment]
@Nefari0uss what's your operating system?

**Comment by Nefari0uss** [comment]
@averissimo I tested this on Arch Linux (x64).

**Comment by averissimo** [comment]
the fix I describe above should should solve it for that linux. https://github.com/yakyak/yakyak/issues/132#issuecomment-242366680

@Nefari0uss if you want out of the box support try `feature-bring-back-noto` branch in my fork

**Comment by Nefari0uss** [comment]
Hmm...I created the .fonts.conf file in my home directory and restarted YakYak (v1.4.1). Still no change.

**Comment by averissimo** [comment]
Thomas yesterday updated the Wiki with some instructions for Arch

https://github.com/yakyak/yakyak/wiki#archlinux
