### ISSUE TITLE
Hide archived chats

### ISSUE THREAD

**Issue by jenil** [yakyak/yakyak#252]

**Comment by jwhipp** [comment]
+1 ... to add to description, archived chats show up as active chats, they should be hidden.

**Comment by psouza4** [comment]
I'd love to see some consideration on this.  Having messages from my ex wife show up there from a year ago is a bummer I see every day via YakYak.

**Comment by davibe** [comment]
Guys #351 #453 #623 #346

**Comment by psouza4** [comment]
I'm not sure why you're linking those issues.  Half of them are closed and refer back to this one -- that's why I commented on this one.  Anyway, would like to see some progress here if possible.  Good luck, contributors!

**Comment by davibe** [comment]
They refer to this one because i have just mentioned them here :D

**Comment by psouza4** [comment]
Please re-open, not everybody uses Hangouts the same way and it's rather important to keep archived chats hidden.  We don't need any special code that toggles them on/off, just simply don't load in or parse chats that are archived when displaying the list, please.

**Comment by psouza4** [comment]
Thank you!

**Comment by averissimo** [comment]
We are showing everything that is sent from the server, with no distinction...

For this to be implemented I think we need someone to:

- In `conv.coffee` create some logic to prevent archive conversations to be shown by using the view property in the conv object which cat take the following values:

`conv.self_conversation_state.view[0] = "VIEW_ARCHIVED" or "VIEW_INBOX" or "VIEW_UNKNOWN"`

Looking for a volunteer to code this :)

**Comment by bsumlin** [comment]
I'm glad this is re-opened! I signed in to YikYak today for the first time. I only use it to talk to my girlfriend and my advisor, but it was showing me chats I hadn't participated in for 3-5 years. Archived chats should be hidden!

**Comment by DavidJSmart** [comment]
The archived chats I have are from when someone moved to a new id (e.g. my daughter started using her married name).  I keep these hidden so I don’t choose them by accident, and also because they are not part of my current set of chats.  But they are still relevant, so I want to access them when I need to.  I have no trouble on my other computers (nor on the Chrome app on the PC).  It’s part of Hangouts, so should be implemented in this app too.  (And it’s hardly difficult to do, surely.)

**Comment by psouza4** [comment]
De-stale please.  Still a big issue... I sometimes get Hangouts spam and can't get rid of the conversation in Yakyak

**Comment by jwhipp** [comment]
I was starting to wonder if Yakyak was abandoned because of lack of activity but I see commits now so perhaps there's hope.  I love it, would love to see it keep getting worked on. 👍

**Comment by DavidJSmart** [comment]
This is still an issue. The Chrome addon does it, and so do the apps on the mobiles. Surely it’s an easy enough facility to add.

**Comment by averissimo** [comment]
It was, I detailed a suggestion on how to do it some time ago.

Should be fixed in https://github.com/averissimo/yakyak/releases/tag/v1.5.0-%23252

Please try it and please let us know if there is any problems with this specific binary.

**Comment by DavidJSmart** [comment]
I've just downloaded 1.5 from that link and the archived conversations 
still appear.

I can't find any setting that controls whether you see them or not. Am I 
missing something?

*Regards, Dave S*

/[Sent from Thunderbird for PC]/

**Comment by averissimo** [comment]
No controls are needed. I've downloaded and worked for me.

Can you try downloading again? *(it was updated)*

If it still does shows the archived conversations then open the inspector (Ctrl+Alt+ i) and check the console tab.

It should show something like:

`status of conv: ARCHIVED_VIEW name1,name2`
`status of conv: INBOX_VIEW name1,name2`

Please check if the lines of the conversations that are supposed to be archived and whether it says `ARCHIVED_VIEW`, `INBOX_VIEW` or something else

**Comment by averissimo** [comment]
In my tests it works as intended and every time I archive a conversation in gmail or unarchive it (by sendind a message) it hides/appears in yakyak.

Again, link is: https://github.com/averissimo/yakyak/releases/tag/v1.5.0-%23252

(it's from my fork on yakyak so I don't overcomplicate yakyak's own release page)

**Comment by DavidJSmart** [comment]
Hi André

I had downloaded Version 1.5.0 shortly after your e-mail announcing the 
change, and it certainly said 1.5.0.  But it was clearly not the right one.

I've just downloaded it again from your latest link, and it's now 
working correctly.

Many thanks for the fix and also for the follow-up.  Much appreciated.

*Regards, Dave S*

/[Sent from Thunderbird for PC]/

**Comment by averissimo** [comment]
I'd ask you to be more attentive on the usage, in particular:

- Message history is being kept correctly
- Badge count (showing number of unread messages) is correct
- Any strange things going on with the conversations

Thanks!

**Comment by jwhipp** [comment]
@averissimo - In terms of the badge count, I opened #859 because I wasn't sure if the change you made was related to that.

**Comment by averissimo** [comment]
It should not be related as it is not in the main code. You did well in opening a separate issue.

**Comment by tghw** [comment]
Did this ever get merged in?

**Comment by CartoonChess** [comment]
It doesn't appear so. I'm hoping for this change as well.
