### ISSUE TITLE
connect_failed TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by cmurf** [yakyak/yakyak#978]
Looks like maybe Google has changed something. It was working fine until this morning, with no updates of anything in between. Looks similar to this: https://github.com/yakyak/yakyak/issues/451#issuecomment-264061983

[chris@flap yakyak]$ git show-ref --heads
ec04e5e9116cc89084a99e97639385a69a76e163 refs/heads/master

I'm on Fedora 29 which has:
nodejs-10.12.0-1.fc29.x86_64
npm-6.4.1-1.10.12.0.1.fc29.x86_64
```
[chris@flap yakyak]$ npm run electron app &
[1] 2300
[chris@flap yakyak]$ 
> yakyak@1.5.2 electron /home/chris/Applications/yakyak
> electron "app"

hconnect
reconnecting 0
resolving proxy http://plus.google.com
resolving proxy https://plus.google.com
resolved proxy DIRECT
resolved proxy DIRECT
connect_failed TypeError: Cannot read property 'length' of undefined
    at /home/chris/Applications/yakyak/app/node_modules/hangupsjs/lib/init.js:125:20
    at _fulfilled (/home/chris/Applications/yakyak/app/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/home/chris/Applications/yakyak/app/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/home/chris/Applications/yakyak/app/node_modules/q/q.js:816:13)
    at /home/chris/Applications/yakyak/app/node_modules/q/q.js:570:49
    at runSingle (/home/chris/Applications/yakyak/app/node_modules/q/q.js:137:13)
    at flush (/home/chris/Applications/yakyak/app/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by tomasz-musialek** [comment]
I've just solved it in the pull request:

https://github.com/yakyak/hangupsjs/pull/102

Related issue, where I explain what needs to be done (possibly a new binary release):

https://github.com/yakyak/yakyak/issues/979

**Comment by Green-Star** [comment]
@tomasz-musialek's fix have solved the issue on my yakyak too :+1:

**Comment by fulltrucker** [comment]
I commented on @tomasz-musialek's issue that his fix works for me as well. Mac OS X El Capitan running on an older MacBook Pro.

**Comment by edraven** [comment]
Did google change it a 3rd time? https://github.com/yakyak/hangupsjs/pull/104/ isn't working for me

**Comment by averissimo** [comment]
This is fixed in v1.5.2 that was just updated and released -- major thanks to contributors of this pull request: https://github.com/yakyak/hangupsjs/pull/104

Please report back if you guys have problems

**Comment by MartinWallgren** [comment]
I'm still getting this error with yakyak-1.5.2-linux-amd64.deb

**Comment by averissimo** [comment]
The fix was for a different error.

@MartinWallgren @cmurf can you guys test something out and report here?

In the file `node_modules/hangupsjs/lib/init.js` line 132

replace the line

```
if (d.length) {
```

```
if (typeof d !== "undefined" && d !== null ? d.length : void 0) {
```

and on line 135 `log.debug` with `console.log`

Run it, see if solves anything and paste the console output here *(please remove any identifying information if it appears)*

**Comment by MartinWallgren** [comment]
FYI, I installed the v1.5.4 Beta and this problem does not exist there.
